### ISSUE TITLE
Cannot build repository with CMake

### ISSUE THREAD

**Issue by Catyre** [LeeTeng2001/metal-cpp-cmake#2]
Hello,
When following the standard CMake procedure for generating outputs of this repository, I run into issues.

Commands run:
```
git clone https://github.com/LeeTeng2001/metal-cpp-cmake
cd metal-cpp-cmake
mkdir build
cd build
cmake ..
make
```

At this point, I get this error:
<img width="1680" alt="Screen Shot 2023-04-19 at 7 45 56 PM" src="https://user-images.githubusercontent.com/7707850/233222963-da4654c5-66ce-4d86-9609-3bdd39584dc3.png">
This is the same problem I have on my own Metal project.  I have no idea what the problem is.  Any help would be appreciated!

**Comment by LeeTeng2001** [comment]
It should be a very standard cmake project, can you check with your compiler generated with cmake?

**Comment by Catyre** [comment]
I found the problem, I was using homebrew-installed g++ instead of clang++.  Switching CMake to use clang++ fixed the issue.
